[package]
name = "graphein-codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.20.11"
quote = "1.0.40"
syn = "2.0.100"
